AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline with S3 Source (AppSpec + TaskDef) and ECS Blue/Green Deployment

Parameters:
  PipelineName:
    Type: String
    Default: PhotoGalleryPipeline

Resources:
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: PhotoGalleryCodeDeployApp
      ComputePlatform: ECS
    DeletionPolicy: Retain

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: PhotoGalleryDeploymentGroup
      ServiceRoleArn: !ImportValue PhotoGalleryCodeDeployRoleArn
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - ProdTrafficRoute:
              ListenerArns:
                - !ImportValue PhotoGalleryListenerArn
            TargetGroups:
              - Name: !ImportValue PhotoGalleryBlueTargetGroupName
              - Name: !ImportValue PhotoGalleryGreenTargetGroupName
      ECSServices:
        - ServiceName: !ImportValue ServiceName
          ClusterName: !ImportValue ClusterName
    DeletionPolicy: Retain

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !ImportValue PhotoGalleryCodePipelineRoleArn
      ArtifactStore:
        Location: !ImportValue PhotoGalleryArtifactBucketName
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: AppSpecSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !ImportValue PhotoGalleryArtifactBucketName
                S3ObjectKey: photo-gallery-bundle.zip
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Deploy
          Actions:
            - Name: ECSBlueGreenDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: '1'
              Configuration:
                ApplicationName: !Ref CodeDeployApp
                DeploymentGroupName: !Ref DeploymentGroup
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

Outputs:
  PipelineName:
    Value: !Ref PipelineName
    Export:
      Name: codepipeline-PipelineName

  CodeDeployAppName:
    Value: !Ref CodeDeployApp
    Export:
      Name: !Sub ${AWS::StackName}-CodeDeployAppName

  DeploymentGroupName:
    Value: !Ref DeploymentGroup
    Export:
      Name: !Sub ${AWS::StackName}-DeploymentGroupName
