AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline with S3 Source (AppSpec + TaskDef) and ECS Blue/Green Deployment

Parameters:
  PipelineName:
    Type: String
    Default: PhotoGalleryPipeline
  CodePipelineRoleArn:
    Type: String
    Description: ARN of the IAM role for CodePipeline
  CodeDeployRoleArn:
    Type: String
    Description: ARN of the IAM role for CodeDeploy
  ListenerArn:
    Type: String

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-photo-gallery-artifacts"
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain

  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: PhotoGalleryCodeDeployApp
      ComputePlatform: ECS
    DeletionPolicy: Retain

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: PhotoGalleryDeploymentGroup
      ServiceRoleArn: !Ref CodeDeployRoleArn
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - ProdTrafficRoute:
              ListenerArns:
                - !Ref ListenerArn
            TargetGroups:
              - Name: !ImportValue alb-BlueTargetGroupArn
              - Name: !ImportValue alb-GreenTargetGroupArn
      ECSServices:
        - ServiceName: !ImportValue ecs-ServiceName
          ClusterName: !ImportValue ecs-ClusterName
    DeletionPolicy: Retain

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: AppSpecSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !Ref ArtifactBucket
                S3ObjectKey: photo-gallery-bundle.zip
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Deploy
          Actions:
            - Name: ECSBlueGreenDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: '1'
              Configuration:
                ApplicationName: !Ref CodeDeployApp
                DeploymentGroupName: !Ref DeploymentGroup
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

Outputs:
  PipelineName:
    Value: !Ref PipelineName
    Export:
      Name: !Sub ${AWS::StackName}-PipelineName
  CodeDeployAppName:
    Value: !Ref CodeDeployApp
    Export:
      Name: !Sub ${AWS::StackName}-CodeDeployAppName
  DeploymentGroupName:
    Value: !Ref DeploymentGroup
    Export:
      Name: !Sub ${AWS::StackName}-DeploymentGroupName
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub ${AWS::StackName}-ArtifactBucketName