AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon RDS PostgreSQL for metadata storage with Secrets Manager

Parameters:
  DbInstanceIdentifier:
    Type: String
    Default: new-photo-gallery-db
    Description: Identifier for the RDS instance

Resources:
  # Security group for ECS tasks (receives traffic from ALB SG)
  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !ImportValue PhotoGalleryVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !ImportValue PhotoGalleryAlbSecurityGroupId
      Tags:
        - Key: Name
          Value: Photo-ECS-SG

  # Security group for RDS (allows Postgres traffic from ECS SG)
  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS
      VpcId: !ImportValue PhotoGalleryVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EcsSecurityGroup
      Tags:
        - Key: Name
          Value: Photo-RDS-SG

  # Subnet group for RDS (use imported private subnets)
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds: !Split [ ",", !ImportValue PhotoGalleryPrivateSubnetIds ]

  # Secrets Manager entry for DB credentials
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /new-photo-gallery/db/credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "administrator"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  # PostgreSQL RDS Instance
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DbInstanceIdentifier
      DBName: photodb
      Engine: postgres
      EngineVersion: '16'
      DBInstanceClass: db.t3.micro
      MasterUsername: !Join ["", ["{{resolve:secretsmanager:", !Ref DBSecret, ":SecretString:username}}"]]
      MasterUserPassword: !Join ["", ["{{resolve:secretsmanager:", !Ref DBSecret, ":SecretString:password}}"]]
      AllocatedStorage: 20
      StorageType: gp3
      VPCSecurityGroups:
        - !Ref RdsSecurityGroup
      DBSubnetGroupName: !Ref DbSubnetGroup
      PubliclyAccessible: false
      MultiAZ: false

Outputs:
  RdsEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: PhotoGalleryRdsEndpoint

  RdsPort:
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: PhotoGalleryRdsPort

  EcsSecurityGroupId:
    Value: !Ref EcsSecurityGroup
    Export:
      Name: PhotoGalleryEcsSecurityGroupId

  RdsSecurityGroupId:
    Value: !Ref RdsSecurityGroup
    Export:
      Name: PhotoGalleryRdsSecurityGroupId

  DBSecretArn:
    Value: !Ref DBSecret
    Export:
      Name: NewPhotoGalleryDBSecretArn
