AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repository for Photo Gallery app image

Parameters:
  RepositoryName:
    Type: String
    Default: photo-gallery-app
    Description: Name of the ECR repository

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: KMS
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images older than 14 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 14
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Keep last 10 tagged images",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["v"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  RepositoryArn:
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: PhotoGalleryecr-RepositoryArn

  RepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: PhotoGalleryecr-RepositoryUri

  RepositoryName:
    Value: !Ref ECRRepository
    Export:
      Name: PhotoGalleryecr-RepositoryName