AWSTemplateFormatVersion: '2010-09-09'
Description: ECS cluster, service, and autoscaling

Parameters:
  ClusterName:
    Type: String
    Default: PhotoGalleryCluster
  TaskCpu:
    Type: String
    Default: 256
  TaskMemory:
    Type: String
    Default: 512

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/photo-gallery
      RetentionInDays: 14

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      Family: photo-gallery-task
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue PhotoGalleryEcsTaskExecutionRoleArn
      TaskRoleArn: !ImportValue PhotoGalleryEcsTaskRoleArn
      ContainerDefinitions:
        - Name: photo-container
          Image: !ImportValue "${PhotoGalleryecr-RepositoryUri}:latest"
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/photo-gallery
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Environment:
            - Name: AWS_S3_BUCKET
              Value: !ImportValue PhotoGalleryStorageBucketName
            - Name: AWS_REGION
              Value: !Ref AWS::Region
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:8080/actuator/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 120        

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: photo-service
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Split [ ',', !ImportValue PhotoGalleryPrivateSubnetIds ]
          SecurityGroups:
            - !ImportValue PhotoGalleryEcsSecurityGroupId
          AssignPublicIp: DISABLED
      LoadBalancers:
        - ContainerName: photo-container
          ContainerPort: 8080
          TargetGroupArn: !ImportValue PhotoGalleryBlueTargetGroupArn
      DeploymentController:
        Type: CODE_DEPLOY

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 4
      MinCapacity: 1
      ResourceId: !Join
        - ''
        - - 'service/'
          - !Ref ECSCluster
          - '/'
          - !GetAtt ECSService.Name
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs



  ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: CpuScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization

Outputs:
  ClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: ClusterName

  ServiceName:
    Value: !GetAtt ECSService.Name
    Export:
      Name: ServiceName

  TaskDefinitionArn:
    Value: !Ref TaskDefinition
    Export:
      Name: TaskDefinitionArn

