AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge rule for ECR push to CodePipeline

Resources:
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger pipeline on ECR image push
      EventPattern:
        source:
          - aws.ecr
        detail-type:
          - ECR Image Action
        detail:
          action-type:
            - PUSH
          repository-name:
            - !ImportValue ecr-RepositoryName
          image-tag:
            - latest
      State: ENABLED
      Targets:
        - Arn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:*!ImportValue codepipeline-PipelineName
          RoleArn: !GetAtt EventRole.Arn
          Id: CodePipelineTarget

  EventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartPipeline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:*!ImportValue codepipeline-PipelineName